/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MaterialInput = IDL.Record({
  'costPerUnit' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'unit' : IDL.Text,
});
export const LocationType = IDL.Variant({
  'site' : IDL.Null,
  'godown' : IDL.Null,
  'company' : IDL.Null,
});
export const BasicLocation = IDL.Record({
  'id' : IDL.Nat,
  'type' : LocationType,
});
export const Direction = IDL.Variant({ 'to' : IDL.Null, 'from' : IDL.Null });
export const PersonDirection = IDL.Variant({
  'direction' : Direction,
  'responsible' : IDL.Null,
});
export const PersonInfo = IDL.Record({
  'direction' : PersonDirection,
  'name' : IDL.Text,
});
export const MovementType = IDL.Variant({
  'outStockCheck' : IDL.Null,
  'fromTo' : IDL.Null,
});
export const MovementInput = IDL.Record({
  'destination' : IDL.Opt(BasicLocation),
  'costPerUnit' : IDL.Opt(IDL.Nat),
  'source' : IDL.Opt(BasicLocation),
  'materialId' : IDL.Nat,
  'personName' : IDL.Opt(PersonInfo),
  'movementType' : MovementType,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'companyId' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'relatedPersonName' : IDL.Opt(IDL.Text),
  'relatedLocation' : IDL.Opt(BasicLocation),
  'photos' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Company = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Godown = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
});
export const Material = IDL.Record({
  'id' : IDL.Nat,
  'costPerUnit' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'unit' : IDL.Text,
});
export const MaterialWithStockInfo = IDL.Record({
  'totalValue' : IDL.Nat,
  'totalIn' : IDL.Nat,
  'totalOut' : IDL.Nat,
  'availableStock' : IDL.Nat,
  'material' : Material,
});
export const Movement = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Opt(BasicLocation),
  'costPerUnit' : IDL.Opt(IDL.Nat),
  'source' : IDL.Opt(BasicLocation),
  'createdAt' : IDL.Int,
  'materialId' : IDL.Nat,
  'personName' : IDL.Opt(PersonInfo),
  'movementType' : MovementType,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'companyId' : IDL.Opt(IDL.Nat),
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'relatedPersonName' : IDL.Opt(IDL.Text),
  'relatedLocation' : IDL.Opt(BasicLocation),
  'photos' : IDL.Vec(ExternalBlob),
});
export const Site = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCompany' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createGodown' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'createMaterial' : IDL.Func([MaterialInput], [IDL.Nat], []),
  'createMovement' : IDL.Func([MovementInput], [IDL.Nat], []),
  'createNote' : IDL.Func([NoteInput], [IDL.Nat], []),
  'createSite' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'deleteCompany' : IDL.Func([IDL.Nat], [], []),
  'deleteGodown' : IDL.Func([IDL.Nat], [], []),
  'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
  'deleteMovement' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteSite' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getCompany' : IDL.Func([IDL.Nat], [IDL.Opt(Company)], ['query']),
  'getGodown' : IDL.Func([IDL.Nat], [IDL.Opt(Godown)], ['query']),
  'getGodowns' : IDL.Func([], [IDL.Vec(Godown)], ['query']),
  'getMaterial' : IDL.Func([IDL.Nat], [IDL.Opt(Material)], ['query']),
  'getMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'getMaterialsWithStockInfo' : IDL.Func(
      [],
      [IDL.Vec(MaterialWithStockInfo)],
      ['query'],
    ),
  'getMovement' : IDL.Func([IDL.Nat], [IDL.Opt(Movement)], ['query']),
  'getMovements' : IDL.Func([], [IDL.Vec(Movement)], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getSite' : IDL.Func([IDL.Nat], [IDL.Opt(Site)], ['query']),
  'getSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
  'getStockForLocation' : IDL.Func(
      [BasicLocation],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCompany' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateGodown' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'updateMaterial' : IDL.Func([IDL.Nat, MaterialInput], [], []),
  'updateMovement' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(BasicLocation),
        IDL.Opt(BasicLocation),
        IDL.Opt(PersonInfo),
        IDL.Opt(IDL.Nat),
        IDL.Int,
      ],
      [],
      [],
    ),
  'updateNote' : IDL.Func([IDL.Nat, NoteInput], [], []),
  'updateSite' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MaterialInput = IDL.Record({
    'costPerUnit' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'unit' : IDL.Text,
  });
  const LocationType = IDL.Variant({
    'site' : IDL.Null,
    'godown' : IDL.Null,
    'company' : IDL.Null,
  });
  const BasicLocation = IDL.Record({ 'id' : IDL.Nat, 'type' : LocationType });
  const Direction = IDL.Variant({ 'to' : IDL.Null, 'from' : IDL.Null });
  const PersonDirection = IDL.Variant({
    'direction' : Direction,
    'responsible' : IDL.Null,
  });
  const PersonInfo = IDL.Record({
    'direction' : PersonDirection,
    'name' : IDL.Text,
  });
  const MovementType = IDL.Variant({
    'outStockCheck' : IDL.Null,
    'fromTo' : IDL.Null,
  });
  const MovementInput = IDL.Record({
    'destination' : IDL.Opt(BasicLocation),
    'costPerUnit' : IDL.Opt(IDL.Nat),
    'source' : IDL.Opt(BasicLocation),
    'materialId' : IDL.Nat,
    'personName' : IDL.Opt(PersonInfo),
    'movementType' : MovementType,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'companyId' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'relatedPersonName' : IDL.Opt(IDL.Text),
    'relatedLocation' : IDL.Opt(BasicLocation),
    'photos' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Company = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Godown = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
  });
  const Material = IDL.Record({
    'id' : IDL.Nat,
    'costPerUnit' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'unit' : IDL.Text,
  });
  const MaterialWithStockInfo = IDL.Record({
    'totalValue' : IDL.Nat,
    'totalIn' : IDL.Nat,
    'totalOut' : IDL.Nat,
    'availableStock' : IDL.Nat,
    'material' : Material,
  });
  const Movement = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Opt(BasicLocation),
    'costPerUnit' : IDL.Opt(IDL.Nat),
    'source' : IDL.Opt(BasicLocation),
    'createdAt' : IDL.Int,
    'materialId' : IDL.Nat,
    'personName' : IDL.Opt(PersonInfo),
    'movementType' : MovementType,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'companyId' : IDL.Opt(IDL.Nat),
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'relatedPersonName' : IDL.Opt(IDL.Text),
    'relatedLocation' : IDL.Opt(BasicLocation),
    'photos' : IDL.Vec(ExternalBlob),
  });
  const Site = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCompany' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createGodown' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'createMaterial' : IDL.Func([MaterialInput], [IDL.Nat], []),
    'createMovement' : IDL.Func([MovementInput], [IDL.Nat], []),
    'createNote' : IDL.Func([NoteInput], [IDL.Nat], []),
    'createSite' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'deleteCompany' : IDL.Func([IDL.Nat], [], []),
    'deleteGodown' : IDL.Func([IDL.Nat], [], []),
    'deleteMaterial' : IDL.Func([IDL.Nat], [], []),
    'deleteMovement' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteSite' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getCompany' : IDL.Func([IDL.Nat], [IDL.Opt(Company)], ['query']),
    'getGodown' : IDL.Func([IDL.Nat], [IDL.Opt(Godown)], ['query']),
    'getGodowns' : IDL.Func([], [IDL.Vec(Godown)], ['query']),
    'getMaterial' : IDL.Func([IDL.Nat], [IDL.Opt(Material)], ['query']),
    'getMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'getMaterialsWithStockInfo' : IDL.Func(
        [],
        [IDL.Vec(MaterialWithStockInfo)],
        ['query'],
      ),
    'getMovement' : IDL.Func([IDL.Nat], [IDL.Opt(Movement)], ['query']),
    'getMovements' : IDL.Func([], [IDL.Vec(Movement)], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getSite' : IDL.Func([IDL.Nat], [IDL.Opt(Site)], ['query']),
    'getSites' : IDL.Func([], [IDL.Vec(Site)], ['query']),
    'getStockForLocation' : IDL.Func(
        [BasicLocation],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCompany' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateGodown' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'updateMaterial' : IDL.Func([IDL.Nat, MaterialInput], [], []),
    'updateMovement' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(BasicLocation),
          IDL.Opt(BasicLocation),
          IDL.Opt(PersonInfo),
          IDL.Opt(IDL.Nat),
          IDL.Int,
        ],
        [],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Nat, NoteInput], [], []),
    'updateSite' : IDL.Func([IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };