/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BasicLocation { 'id' : bigint, 'type' : LocationType }
export interface Company { 'id' : bigint, 'name' : string }
export type Direction = { 'to' : null } |
  { 'from' : null };
export type ExternalBlob = Uint8Array;
export interface Godown {
  'id' : bigint,
  'name' : string,
  'location' : [] | [string],
}
export type LocationType = { 'site' : null } |
  { 'godown' : null } |
  { 'company' : null };
export interface Material {
  'id' : bigint,
  'costPerUnit' : [] | [bigint],
  'name' : string,
  'unit' : string,
}
export interface MaterialInput {
  'costPerUnit' : [] | [bigint],
  'name' : string,
  'unit' : string,
}
export interface MaterialWithStockInfo {
  'totalValue' : bigint,
  'totalIn' : bigint,
  'totalOut' : bigint,
  'availableStock' : bigint,
  'material' : Material,
}
export interface Movement {
  'id' : bigint,
  'destination' : [] | [BasicLocation],
  'costPerUnit' : [] | [bigint],
  'source' : [] | [BasicLocation],
  'createdAt' : bigint,
  'materialId' : bigint,
  'personName' : [] | [PersonInfo],
  'movementType' : MovementType,
  'timestamp' : bigint,
  'quantity' : bigint,
  'companyId' : [] | [bigint],
}
export interface MovementInput {
  'destination' : [] | [BasicLocation],
  'costPerUnit' : [] | [bigint],
  'source' : [] | [BasicLocation],
  'materialId' : bigint,
  'personName' : [] | [PersonInfo],
  'movementType' : MovementType,
  'timestamp' : bigint,
  'quantity' : bigint,
  'companyId' : [] | [bigint],
}
export type MovementType = { 'outStockCheck' : null } |
  { 'fromTo' : null };
export interface Note {
  'id' : bigint,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'relatedPersonName' : [] | [string],
  'relatedLocation' : [] | [BasicLocation],
  'photos' : Array<ExternalBlob>,
}
export interface NoteInput {
  'title' : string,
  'description' : string,
  'relatedPersonName' : [] | [string],
  'relatedLocation' : [] | [BasicLocation],
  'photos' : Array<ExternalBlob>,
}
export type PersonDirection = { 'direction' : Direction } |
  { 'responsible' : null };
export interface PersonInfo { 'direction' : PersonDirection, 'name' : string }
export interface Site {
  'id' : bigint,
  'name' : string,
  'location' : [] | [string],
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCompany' : ActorMethod<[string], bigint>,
  'createGodown' : ActorMethod<[string, [] | [string]], bigint>,
  'createMaterial' : ActorMethod<[MaterialInput], bigint>,
  'createMovement' : ActorMethod<[MovementInput], bigint>,
  'createNote' : ActorMethod<[NoteInput], bigint>,
  'createSite' : ActorMethod<[string, [] | [string]], bigint>,
  'deleteCompany' : ActorMethod<[bigint], undefined>,
  'deleteGodown' : ActorMethod<[bigint], undefined>,
  'deleteMaterial' : ActorMethod<[bigint], undefined>,
  'deleteMovement' : ActorMethod<[bigint], undefined>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteSite' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanies' : ActorMethod<[], Array<Company>>,
  'getCompany' : ActorMethod<[bigint], [] | [Company]>,
  'getGodown' : ActorMethod<[bigint], [] | [Godown]>,
  'getGodowns' : ActorMethod<[], Array<Godown>>,
  'getMaterial' : ActorMethod<[bigint], [] | [Material]>,
  'getMaterials' : ActorMethod<[], Array<Material>>,
  'getMaterialsWithStockInfo' : ActorMethod<[], Array<MaterialWithStockInfo>>,
  'getMovement' : ActorMethod<[bigint], [] | [Movement]>,
  'getMovements' : ActorMethod<[], Array<Movement>>,
  'getNote' : ActorMethod<[bigint], [] | [Note]>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getSite' : ActorMethod<[bigint], [] | [Site]>,
  'getSites' : ActorMethod<[], Array<Site>>,
  'getStockForLocation' : ActorMethod<[BasicLocation], Array<[bigint, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCompany' : ActorMethod<[bigint, string], undefined>,
  'updateGodown' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'updateMaterial' : ActorMethod<[bigint, MaterialInput], undefined>,
  'updateMovement' : ActorMethod<
    [
      bigint,
      bigint,
      [] | [BasicLocation],
      [] | [BasicLocation],
      [] | [PersonInfo],
      [] | [bigint],
      bigint,
    ],
    undefined
  >,
  'updateNote' : ActorMethod<[bigint, NoteInput], undefined>,
  'updateSite' : ActorMethod<[bigint, string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];