/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BasicLocation {
    id: bigint;
    type: LocationType;
}
export interface PersonInfo {
    direction: PersonDirection;
    name: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MaterialWithStockInfo {
    totalValue: bigint;
    totalIn: bigint;
    totalOut: bigint;
    availableStock: bigint;
    material: Material;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type PersonDirection = {
    __kind__: "direction";
    direction: Direction;
} | {
    __kind__: "responsible";
    responsible: null;
};
export interface Company {
    id: bigint;
    name: string;
}
export interface MaterialInput {
    costPerUnit?: bigint;
    name: string;
    unit: string;
}
export interface Material {
    id: bigint;
    costPerUnit?: bigint;
    name: string;
    unit: string;
}
export interface Godown {
    id: bigint;
    name: string;
    location?: string;
}
export interface NoteInput {
    title: string;
    description: string;
    relatedPersonName?: string;
    relatedLocation?: BasicLocation;
    photos: Array<ExternalBlob>;
}
export interface Site {
    id: bigint;
    name: string;
    location?: string;
}
export interface MovementInput {
    destination?: BasicLocation;
    costPerUnit?: bigint;
    source?: BasicLocation;
    materialId: bigint;
    personName?: PersonInfo;
    movementType: MovementType;
    timestamp: bigint;
    quantity: bigint;
    companyId?: bigint;
}
export interface Movement {
    id: bigint;
    destination?: BasicLocation;
    costPerUnit?: bigint;
    source?: BasicLocation;
    createdAt: bigint;
    materialId: bigint;
    personName?: PersonInfo;
    movementType: MovementType;
    timestamp: bigint;
    quantity: bigint;
    companyId?: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface Note {
    id: bigint;
    title: string;
    date: bigint;
    description: string;
    relatedPersonName?: string;
    relatedLocation?: BasicLocation;
    photos: Array<ExternalBlob>;
}
export enum Direction {
    to = "to",
    from = "from"
}
export enum LocationType {
    site = "site",
    godown = "godown",
    company = "company"
}
export enum MovementType {
    outStockCheck = "outStockCheck",
    fromTo = "fromTo"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCompany(name: string): Promise<bigint>;
    createGodown(name: string, location: string | null): Promise<bigint>;
    createMaterial(input: MaterialInput): Promise<bigint>;
    createMovement(input: MovementInput): Promise<bigint>;
    createNote(input: NoteInput): Promise<bigint>;
    createSite(name: string, location: string | null): Promise<bigint>;
    deleteCompany(id: bigint): Promise<void>;
    deleteGodown(id: bigint): Promise<void>;
    deleteMaterial(id: bigint): Promise<void>;
    deleteMovement(movementId: bigint): Promise<void>;
    deleteNote(id: bigint): Promise<void>;
    deleteSite(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanies(): Promise<Array<Company>>;
    getCompany(id: bigint): Promise<Company | null>;
    getGodown(id: bigint): Promise<Godown | null>;
    getGodowns(): Promise<Array<Godown>>;
    getMaterial(id: bigint): Promise<Material | null>;
    getMaterials(): Promise<Array<Material>>;
    getMaterialsWithStockInfo(): Promise<Array<MaterialWithStockInfo>>;
    getMovement(id: bigint): Promise<Movement | null>;
    getMovements(): Promise<Array<Movement>>;
    getNote(id: bigint): Promise<Note | null>;
    getNotes(): Promise<Array<Note>>;
    getSite(id: bigint): Promise<Site | null>;
    getSites(): Promise<Array<Site>>;
    getStockForLocation(location: BasicLocation): Promise<Array<[bigint, bigint]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCompany(id: bigint, name: string): Promise<void>;
    updateGodown(id: bigint, name: string, location: string | null): Promise<void>;
    updateMaterial(id: bigint, input: MaterialInput): Promise<void>;
    updateMovement(id: bigint, quantity: bigint, source: BasicLocation | null, destination: BasicLocation | null, personName: PersonInfo | null, costPerUnit: bigint | null, timestamp: bigint): Promise<void>;
    updateNote(id: bigint, input: NoteInput): Promise<void>;
    updateSite(id: bigint, name: string, location: string | null): Promise<void>;
}
import type { BasicLocation as _BasicLocation, Company as _Company, Direction as _Direction, ExternalBlob as _ExternalBlob, Godown as _Godown, LocationType as _LocationType, Material as _Material, MaterialInput as _MaterialInput, MaterialWithStockInfo as _MaterialWithStockInfo, Movement as _Movement, MovementInput as _MovementInput, MovementType as _MovementType, Note as _Note, NoteInput as _NoteInput, PersonDirection as _PersonDirection, PersonInfo as _PersonInfo, Site as _Site, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCompany(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompany(arg0);
            return result;
        }
    }
    async createGodown(arg0: string, arg1: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGodown(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGodown(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMaterial(arg0: MaterialInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMaterial(to_candid_MaterialInput_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMaterial(to_candid_MaterialInput_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMovement(arg0: MovementInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMovement(to_candid_MovementInput_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMovement(to_candid_MovementInput_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNote(arg0: NoteInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(await to_candid_NoteInput_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(await to_candid_NoteInput_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSite(arg0: string, arg1: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSite(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSite(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCompany(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCompany(arg0);
            return result;
        }
    }
    async deleteGodown(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGodown(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGodown(arg0);
            return result;
        }
    }
    async deleteMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaterial(arg0);
            return result;
        }
    }
    async deleteMovement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMovement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMovement(arg0);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteSite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSite(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanies(): Promise<Array<Company>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanies();
            return result;
        }
    }
    async getCompany(arg0: bigint): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompany(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompany(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGodown(arg0: bigint): Promise<Godown | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGodown(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGodown(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGodowns(): Promise<Array<Godown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGodowns();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGodowns();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterial(arg0: bigint): Promise<Material | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterial(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterial(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterials(): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterials();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterials();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterialsWithStockInfo(): Promise<Array<MaterialWithStockInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialsWithStockInfo();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialsWithStockInfo();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMovement(arg0: bigint): Promise<Movement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovement(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovement(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMovements(): Promise<Array<Movement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMovements();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMovements();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNote(arg0: bigint): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSite(arg0: bigint): Promise<Site | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSite(arg0);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSite(arg0);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSites(): Promise<Array<Site>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSites();
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSites();
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockForLocation(arg0: BasicLocation): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockForLocation(to_candid_BasicLocation_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockForLocation(to_candid_BasicLocation_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n76(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n76(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCompany(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompany(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompany(arg0, arg1);
            return result;
        }
    }
    async updateGodown(arg0: bigint, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGodown(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGodown(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateMaterial(arg0: bigint, arg1: MaterialInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaterial(arg0, to_candid_MaterialInput_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaterial(arg0, to_candid_MaterialInput_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMovement(arg0: bigint, arg1: bigint, arg2: BasicLocation | null, arg3: BasicLocation | null, arg4: PersonInfo | null, arg5: bigint | null, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMovement(arg0, arg1, to_candid_opt_n78(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n78(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n79(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n80(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMovement(arg0, arg1, to_candid_opt_n78(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n78(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n79(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n80(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateNote(arg0: bigint, arg1: NoteInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, await to_candid_NoteInput_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, await to_candid_NoteInput_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSite(arg0: bigint, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSite(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSite(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_BasicLocation_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BasicLocation): BasicLocation {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Direction_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Direction): Direction {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Godown_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Godown): Godown {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_LocationType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocationType): LocationType {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_MaterialWithStockInfo_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaterialWithStockInfo): MaterialWithStockInfo {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Material_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Material): Material {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_MovementType_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MovementType): MovementType {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Movement_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Movement): Movement {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_Note_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Promise<Note> {
    return await from_candid_record_n69(_uploadFile, _downloadFile, value);
}
function from_candid_PersonDirection_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonDirection): PersonDirection {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_PersonInfo_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonInfo): PersonInfo {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Site_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Site): Site {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Company]): Company | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Godown]): Godown | null {
    return value.length === 0 ? null : from_candid_Godown_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Material]): Material | null {
    return value.length === 0 ? null : from_candid_Material_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Movement]): Movement | null {
    return value.length === 0 ? null : from_candid_Movement_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BasicLocation]): BasicLocation | null {
    return value.length === 0 ? null : from_candid_BasicLocation_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersonInfo]): PersonInfo | null {
    return value.length === 0 ? null : from_candid_PersonInfo_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Promise<Note | null> {
    return value.length === 0 ? null : await from_candid_Note_n68(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Site]): Site | null {
    return value.length === 0 ? null : from_candid_Site_n74(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    location: [] | [string];
}): {
    id: bigint;
    name: string;
    location?: string;
} {
    return {
        id: value.id,
        name: value.name,
        location: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    costPerUnit: [] | [bigint];
    name: string;
    unit: string;
}): {
    id: bigint;
    costPerUnit?: bigint;
    name: string;
    unit: string;
} {
    return {
        id: value.id,
        costPerUnit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.costPerUnit)),
        name: value.name,
        unit: value.unit
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValue: bigint;
    totalIn: bigint;
    totalOut: bigint;
    availableStock: bigint;
    material: _Material;
}): {
    totalValue: bigint;
    totalIn: bigint;
    totalOut: bigint;
    availableStock: bigint;
    material: Material;
} {
    return {
        totalValue: value.totalValue,
        totalIn: value.totalIn,
        totalOut: value.totalOut,
        availableStock: value.availableStock,
        material: from_candid_Material_n43(_uploadFile, _downloadFile, value.material)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    destination: [] | [_BasicLocation];
    costPerUnit: [] | [bigint];
    source: [] | [_BasicLocation];
    createdAt: bigint;
    materialId: bigint;
    personName: [] | [_PersonInfo];
    movementType: _MovementType;
    timestamp: bigint;
    quantity: bigint;
    companyId: [] | [bigint];
}): {
    id: bigint;
    destination?: BasicLocation;
    costPerUnit?: bigint;
    source?: BasicLocation;
    createdAt: bigint;
    materialId: bigint;
    personName?: PersonInfo;
    movementType: MovementType;
    timestamp: bigint;
    quantity: bigint;
    companyId?: bigint;
} {
    return {
        id: value.id,
        destination: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.destination)),
        costPerUnit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.costPerUnit)),
        source: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.source)),
        createdAt: value.createdAt,
        materialId: value.materialId,
        personName: record_opt_to_undefined(from_candid_opt_n57(_uploadFile, _downloadFile, value.personName)),
        movementType: from_candid_MovementType_n64(_uploadFile, _downloadFile, value.movementType),
        timestamp: value.timestamp,
        quantity: value.quantity,
        companyId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.companyId))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    type: _LocationType;
}): {
    id: bigint;
    type: LocationType;
} {
    return {
        id: value.id,
        type: from_candid_LocationType_n55(_uploadFile, _downloadFile, value.type)
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _PersonDirection;
    name: string;
}): {
    direction: PersonDirection;
    name: string;
} {
    return {
        direction: from_candid_PersonDirection_n60(_uploadFile, _downloadFile, value.direction),
        name: value.name
    };
}
async function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: bigint;
    description: string;
    relatedPersonName: [] | [string];
    relatedLocation: [] | [_BasicLocation];
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    title: string;
    date: bigint;
    description: string;
    relatedPersonName?: string;
    relatedLocation?: BasicLocation;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        relatedPersonName: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.relatedPersonName)),
        relatedLocation: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.relatedLocation)),
        photos: await from_candid_vec_n70(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    site: null;
} | {
    godown: null;
} | {
    company: null;
}): LocationType {
    return "site" in value ? LocationType.site : "godown" in value ? LocationType.godown : "company" in value ? LocationType.company : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _Direction;
} | {
    responsible: null;
}): {
    __kind__: "direction";
    direction: Direction;
} | {
    __kind__: "responsible";
    responsible: null;
} {
    return "direction" in value ? {
        __kind__: "direction",
        direction: from_candid_Direction_n62(_uploadFile, _downloadFile, value.direction)
    } : "responsible" in value ? {
        __kind__: "responsible",
        responsible: value.responsible
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: null;
} | {
    from: null;
}): Direction {
    return "to" in value ? Direction.to : "from" in value ? Direction.from : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outStockCheck: null;
} | {
    fromTo: null;
}): MovementType {
    return "outStockCheck" in value ? MovementType.outStockCheck : "fromTo" in value ? MovementType.fromTo : value;
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Godown>): Array<Godown> {
    return value.map((x)=>from_candid_Godown_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Material>): Array<Material> {
    return value.map((x)=>from_candid_Material_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaterialWithStockInfo>): Array<MaterialWithStockInfo> {
    return value.map((x)=>from_candid_MaterialWithStockInfo_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Movement>): Array<Movement> {
    return value.map((x)=>from_candid_Movement_n50(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n71(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Promise<Array<Note>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Note_n68(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Site>): Array<Site> {
    return value.map((x)=>from_candid_Site_n74(_uploadFile, _downloadFile, x));
}
function to_candid_BasicLocation_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BasicLocation): _BasicLocation {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Direction_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): _Direction {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LocationType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationType): _LocationType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_MaterialInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialInput): _MaterialInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_MovementInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementInput): _MovementInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_MovementType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementType): _MovementType {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function to_candid_NoteInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteInput): Promise<_NoteInput> {
    return await to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_PersonDirection_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonDirection): _PersonDirection {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_PersonInfo_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonInfo): _PersonInfo {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BasicLocation | null): [] | [_BasicLocation] {
    return value === null ? candid_none() : candid_some(to_candid_BasicLocation_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonInfo | null): [] | [_PersonInfo] {
    return value === null ? candid_none() : candid_some(to_candid_PersonInfo_n19(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    costPerUnit?: bigint;
    name: string;
    unit: string;
}): {
    costPerUnit: [] | [bigint];
    name: string;
    unit: string;
} {
    return {
        costPerUnit: value.costPerUnit ? candid_some(value.costPerUnit) : candid_none(),
        name: value.name,
        unit: value.unit
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination?: BasicLocation;
    costPerUnit?: bigint;
    source?: BasicLocation;
    materialId: bigint;
    personName?: PersonInfo;
    movementType: MovementType;
    timestamp: bigint;
    quantity: bigint;
    companyId?: bigint;
}): {
    destination: [] | [_BasicLocation];
    costPerUnit: [] | [bigint];
    source: [] | [_BasicLocation];
    materialId: bigint;
    personName: [] | [_PersonInfo];
    movementType: _MovementType;
    timestamp: bigint;
    quantity: bigint;
    companyId: [] | [bigint];
} {
    return {
        destination: value.destination ? candid_some(to_candid_BasicLocation_n15(_uploadFile, _downloadFile, value.destination)) : candid_none(),
        costPerUnit: value.costPerUnit ? candid_some(value.costPerUnit) : candid_none(),
        source: value.source ? candid_some(to_candid_BasicLocation_n15(_uploadFile, _downloadFile, value.source)) : candid_none(),
        materialId: value.materialId,
        personName: value.personName ? candid_some(to_candid_PersonInfo_n19(_uploadFile, _downloadFile, value.personName)) : candid_none(),
        movementType: to_candid_MovementType_n25(_uploadFile, _downloadFile, value.movementType),
        timestamp: value.timestamp,
        quantity: value.quantity,
        companyId: value.companyId ? candid_some(value.companyId) : candid_none()
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    type: LocationType;
}): {
    id: bigint;
    type: _LocationType;
} {
    return {
        id: value.id,
        type: to_candid_LocationType_n17(_uploadFile, _downloadFile, value.type)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: PersonDirection;
    name: string;
}): {
    direction: _PersonDirection;
    name: string;
} {
    return {
        direction: to_candid_PersonDirection_n21(_uploadFile, _downloadFile, value.direction),
        name: value.name
    };
}
async function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    relatedPersonName?: string;
    relatedLocation?: BasicLocation;
    photos: Array<ExternalBlob>;
}): Promise<{
    title: string;
    description: string;
    relatedPersonName: [] | [string];
    relatedLocation: [] | [_BasicLocation];
    photos: Array<_ExternalBlob>;
}> {
    return {
        title: value.title,
        description: value.description,
        relatedPersonName: value.relatedPersonName ? candid_some(value.relatedPersonName) : candid_none(),
        relatedLocation: value.relatedLocation ? candid_some(to_candid_BasicLocation_n15(_uploadFile, _downloadFile, value.relatedLocation)) : candid_none(),
        photos: await to_candid_vec_n29(_uploadFile, _downloadFile, value.photos)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LocationType): {
    site: null;
} | {
    godown: null;
} | {
    company: null;
} {
    return value == LocationType.site ? {
        site: null
    } : value == LocationType.godown ? {
        godown: null
    } : value == LocationType.company ? {
        company: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "direction";
    direction: Direction;
} | {
    __kind__: "responsible";
    responsible: null;
}): {
    direction: _Direction;
} | {
    responsible: null;
} {
    return value.__kind__ === "direction" ? {
        direction: to_candid_Direction_n23(_uploadFile, _downloadFile, value.direction)
    } : value.__kind__ === "responsible" ? {
        responsible: value.responsible
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Direction): {
    to: null;
} | {
    from: null;
} {
    return value == Direction.to ? {
        to: null
    } : value == Direction.from ? {
        from: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementType): {
    outStockCheck: null;
} | {
    fromTo: null;
} {
    return value == MovementType.outStockCheck ? {
        outStockCheck: null
    } : value == MovementType.fromTo ? {
        fromTo: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n30(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
